### ISSUE TITLE
Error while trying to add Grid categories

### ISSUE THREAD

**Issue by ArijitWeird** [wharton/wagtailgridder#3]
Hello,
I have followed instructions as given in installation guide. After successful migrations , I have tried to add Grid Categories through admin and get this below error.

Request Method: | GET
-- | --
<host-name>/admin/wagtailgridder/gridcategory/
django version 2.0.4
TemplateDoesNotExist
modeladmin/wagtailgridder/gridcategory/index.html, modeladmin/wagtailgridder/index.html, modeladmin/index.html
/home/ubuntu/lib/python3.5/site-packages/django/template/loader.py in select_template, line 47
/home/ubuntu/bin/python3
python version 3.5.2

Template-loader postmortem
Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/django/contrib/admin/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/django/contrib/auth/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/contrib/forms/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/contrib/redirects/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/embeds/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/sites/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/users/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/snippets/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/documents/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/images/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/search/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/admin/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtail/core/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/wagtailgridder/templates/modeladmin/wagtailgridder/gridcategory/index.html (Source does not exist)

wagtail==2.0.1
wagtailgridder==0.9.28

It seems it cannot find template file or template file migh not be in order.
Any help is  appreciated

**Comment by FlipperPA** [comment]
Ah, I missed something in the docs, thanks for pointing it out.

I believe you need to add `wagtail.contrib.modeladmin` to your `INSTALLED_APPS`. I have updated the README. Can you give that a try and confirm if it works? If it doesn't, can you include your list of `INSTALLED_APPS`? Thank you!

**Comment by ArijitWeird** [comment]
Thanks a lot .. Much love for such a prompt reply.

**Comment by ArijitWeird** [comment]
I proceed as per document instruction and get an error.
TemplateDoesNotExist at /
base.html
Template-loader postmortem
Django tried loading these templates, in this order:
Using engine django:
    django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/django/contrib/admin/templates/base.html (Source does not exist)
    django.template.loaders.app_directories.Loader: /home/ubuntu/lib/python3.5/site-packages/django/contrib/auth/templates/base.html (Source does not exist)

Does I need to create any base template as I understand that grid_index_page.html extends some base.html file. For my above understanding be true, where should we put base.html in my project 
Note: My  django project was first created (without wagtail default project creation) and wagtailgriddder being integrated after that .
I have also set up one wagtail project and implement same thing (added configuration to base.py) , in that case the grid index page is showing nothing ,probably extending base.html file only.
Please suggest.

**Comment by FlipperPA** [comment]
Yes, this package is meant to extend your `base.html` template from your Django project, which typically contains your top and bottom navigation. If you haven't done this before:

- Create a directory called `templates` at the root of your project.
- Create a file in `templates` called `templates/base.html` - eventually, this will where you put your navigation - a sort of master template for your site.

Then, in your settings, in the templates section:

```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        ...(rest of your template settings here)...
    },
]
```

Have you been through the Django tutorial, btw? We'll get you through this, I may add more documentation for a standard project set up.

**Comment by ArijitWeird** [comment]
Thanks FlipperPA. Yes I have read documentation and have been using django for a year , still a beginner I guess. Onething I wish to add here, wagtailgridder can include a base.html file itself in its template directory with some very basic layout. In documentation we may add overiding default  base template by adding the steps you mention above.

**Comment by FlipperPA** [comment]
Ask and ye shall receive! I've put an example `base.html` in the repo, which WagtailGridder will fall back to if none is provided. It is linked from the documentation, @ArijitWeird - I hope it helps.
