### ISSUE TITLE
Documentation potentially out of date: regards is_faculty

### ISSUE THREAD

**Issue by rgs258** [wharton/wagtailgridder#8]
https://github.com/wharton/wagtailgridder/blob/4b5aae898c9ca62cfe1981108c754fafb637814d/wagtailgridder/wagtail_hooks.py#L49

**Comment by rgs258** [comment]
https://github.com/wharton/wagtailgridder/blob/32fc2e75aceb73a3f95594dd1abfb460c9f279b5/wagtailgridder/templates/wagtailgridder/grid_index_page.html#L48

**Comment by FlipperPA** [comment]
This has been fixed - thank you! :)
